### ISSUE TITLE
[build] Drop Multiple Definition Flag from Build

### ISSUE THREAD

**Issue by ppenna** [nanvix/build#4]
# Description

Currently, in order to build the microkernel for the QEMU OpenRISC and QEMU x86 targets we should enable multiple definitions by the compiler.

This seems to be due to some circular requirement in the build system, which we should double check.

# Update

- Enhancement introduced in commit c16a9d9cf637a4cdc9dbb4e4c27aac9d4f5edb1b.
